### ISSUE TITLE
The field type "<field_name>" does not exist

### ISSUE THREAD

**Issue by iv-agatha** [sylvainjule/kirby-locator#22]
I'm using Kirby 3.2.2 and getting this error when using the locator field. This is what my blueprint looks like:

```
title: Location

tabs:
  content:
    label: Content
    icon: document
    columns:
      - width: 2/3
        fields:
          page_content:
            label: Text
            type: textarea
            size: small
          mymap:
            label: Map
            type: locator
```

![image](https://user-images.githubusercontent.com/22304204/61495769-edfd7280-a987-11e9-8a7a-8bf802e75dfe.png)
