### ISSUE TITLE
Locator options in Structure field

### ISSUE THREAD

**Issue by manuelvonrotz** [sylvainjule/kirby-locator#26]
When used in a Structure Field, the options settings don't seem to work

```yaml
locations:
  label: Locations
  type: structure
    fields:
      coordinates:
        label: Location
        type: locator
        draggable: false # <- Still draggable
```

Does also not work,  if I set the options globally in the config file.
