### ISSUE TITLE
Error: The locator field is missing. Please add it to your installed fields or remove it from your blueprint

### ISSUE THREAD

**Issue by maximelebreton** [sylvainjule/kirby-locator#28]
Hello @sylvainjule ,

After a clean install of kirby-webpack, I tried to install your plugin, but have this message:   
`The locator field is missing. Please add it to your installed fields or remove it from your blueprint`

![image](https://user-images.githubusercontent.com/1072425/74547550-92f72280-4f4c-11ea-86dc-418356851c6b.png)

Here is my blueprint:
```yml
title: Step
preset: page
pages: false

fields:
  map:
    label: Location
    type: locator

```
I'm in the right folder:
![image](https://user-images.githubusercontent.com/1072425/74547751-e9fcf780-4f4c-11ea-9325-12a27562e31e.png)

Don't understand what's going on....

Thanks for your help!
