### ISSUE TITLE
The field type "location" does not exist

### ISSUE THREAD

**Issue by medienbaecker** [sylvainjule/kirby-locator#5]
While the plugin is correctly installed (and other plugins work fine) I somethow get the following error message with the latest nightly build:

![image](https://user-images.githubusercontent.com/7975568/48557780-f0cf3180-e8e7-11e8-9726-37c6be5e8a27.png)

"location" is the field name, not field type, in this case:

```yaml
fields:
  location:
    type: locator
```
