### ISSUE TITLE
4.0 Compatibility

### ISSUE THREAD

**Issue by afbora** [sylvainjule/kirby-locator#57]
Tested on 4.0.0-alpha.3 and working great! There is just minor UI issue:

 - Dialog UI

![screen-capture-1610-Test - Mægazine-localhost](https://github.com/sylvainjule/kirby-locator/assets/3393422/ebcc46b6-73f9-4cb9-a287-a934e462e624)
- Reset button position
- Empty text icon size

**Comment by nmanngit** [comment]
I just created #58 to address the dialog UI and resolve a breaking change introduced in alpha 4. While working on it, I also encountered some more UI bugs. However, I'm unsure whether these should be handled within this repo or reported to the Kirby repo. They happen due to these CSS overrides:

```CSS
/* Causes locator icon to shrink which feels unintuitive */
:where(img,picture,svg) {
    max-inline-size: 100%;
}

/* Causes leaflet flag icon to move to a separate line. Note leaflet is an external dependency */
:where(img,svg,video,canvas,audio,iframe,embed,object) {
    display: block;
}
```

What do you think?
