### ISSUE TITLE
K5: dark mode support (quick fix with custom Panel CSS)

### ISSUE THREAD

**Issue by distantnative** [sylvainjule/kirby-locator#63]
While the plugin seems to work with Kirby 5 generally, there are some glitches with the new dark mode. A PR exists https://github.com/sylvainjule/kirby-locator/pull/61/files but while it remains unmerged maybe the following custom Panel CSS can help users in dire need of a solution:

```css
.k-locator-container {
	border-radius: var(--rounded);
	overflow: hidden;
}
.k-locator-field .content {
	background-color: light-dark(
		var(--color-gray-100),
		var(--color-gray-850, var(--color-gray-800))
	);
}
.k-locator-field .k-locator-input button.disabled {
	background: light-dark(var(--color-gray-100), var(--color-gray-800));
}
```
